name = "ten10-email-router"
main = "email-worker.js"
compatibility_date = "2024-01-01"

[vars]
# Non-sensitive variables can be kept in source control to avoid
# accidental deletion during Git-based deployments.

SUPABASE_FUNCTION_URL = "https://flpzqbvbymoluoeeeofg.supabase.co/functions/v1/process-email-request"


[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true